replicaCount: 1

image:
  repository: hello-fastapi
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  create: true
  automount: true
  name: ""

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /health
    port: http

readinessProbe:
  httpGet:
    path: /ready
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

nodeSelector:
  kubernetes.io/arch: amd64
  "eks.amazonaws.com/compute-type": "fargate"

tolerations: []
affinity: {}